feat: tags filter
codemate-oj/codemate-core pull request #26
Opened 2024-05-23 16:48 UTC by StupidQu

2024-05-23 17:06 UTC, KiritoKing approved these changes

2024-05-24 10:58 UTC, KiritoKing requested changes

2024-05-24 10:58 UTC, KiritoKing commented on packages/codemate-plugin/plugins/tags-filter/index.ts
> +        lodash.memoize.Cache = class extends LRUCache<string[], string[]> {
不要把string[]当成键吧 要么hash一下 要么stringify一下

2024-05-24 10:58 UTC, KiritoKing commented on packages/codemate-plugin/plugins/tags-filter/index.ts
> +        global.Hydro.lib.tagsFilter = lodash.memoize((tags: string[]) =>
加一个resolver字段 要么hash一下 要么stringify一下

2024-05-24 10:58 UTC, KiritoKing commented on packages/codemate-plugin/plugins/tags-filter/index.ts
> +        global.Hydro.lib.tagsFilterProcessOne = (pdoc: ProblemDoc) => ({
rename to `filterProblemTags`

2024-05-24 10:58 UTC, KiritoKing commented on packages/codemate-plugin/plugins/tags-filter/index.ts
> +        c.on('handler/after', (that) => {
这里需要覆盖哪些情况给我说明一下

2024-05-24 10:58 UTC, KiritoKing commented on packages/hydrooj/src/handler/problem.ts
> +                            pdocs: pdocs.map((pdoc) => global.Hydro.lib.tagsFilterProcessOne(pdoc)),
这个上面的不能覆盖吗？

2024-05-24 11:10 UTC, StupidQu commented on packages/codemate-plugin/plugins/tags-filter/index.ts
> +        c.on('handler/after', (that) => {
所有需要返回 pdoc 的情况

2024-05-24 11:10 UTC, StupidQu commented on packages/hydrooj/src/handler/problem.ts
> +                            pdocs: pdocs.map((pdoc) => global.Hydro.lib.tagsFilterProcessOne(pdoc)),
不能，这个东西是直接用于了 renderHTML

2024-06-05 17:56 UTC, KiritoKing approved these changes

2024-06-05 17:56 UTC, merged