feat: lost password
codemate-oj/codemate-core pull request #42
Opened 2024-07-12 14:15 UTC by StupidQu

2024-07-12 17:32 UTC, KiritoKing requested changes

2024-07-12 17:32 UTC, KiritoKing commented on packages/codemate-plugin/plugins/lostpass/index.ts
> +            await global.Hydro.lib.mail.sendMail(emailOrPhone, 'Codemate 注册验证码', 'Codemate 注册验证码', html);
不是找回密码吗

2024-07-12 17:32 UTC, KiritoKing commented on packages/hydrooj/src/upgrade.ts
> +    async function _88_89() {
这是什么 你要把手机号的存储格式全换了吗 要改去那边改吧

2024-07-12 17:32 UTC, KiritoKing commented on packages/hydrooj/src/upgrade.ts
> +    async function _88_89() {
不然重构迁移堆积的要改的数据格式太多了啊

2024-07-12 17:32 UTC, KiritoKing commented on packages/hydrooj/src/upgrade.ts
> +    async function _88_89() {
要不这个先缓缓

2024-07-13 00:56 UTC, StupidQu commented on packages/hydrooj/src/upgrade.ts
> +    async function _88_89() {
这只是复制一份放到 udoc.phoneNumber 而已吧，原先 mob-xxx@hydro.local 也能用

2024-07-15 06:03 UTC, KiritoKing approved these changes
lgtm

2024-07-15 06:03 UTC, merged